version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    restart: on-failure
    volumes:
      - ./compose-data/postgres-db:/var/lib/pgsql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgresql-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    container_name: application
    build:
      dockerfile: Dockerfile-back
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - postgresql-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres-db:
        condition: service_healthy

networks:
  postgresql-net:
    driver: bridge
